### ISSUE TITLE
Is `git revert` possible?

### ISSUE THREAD

**Issue by TheLostLambda** [altsem/gitu#110]
Hi @altsem ! I could just be missing the option, but is it possible through the UI to create a `revert` commit?

I've seen there are a couple of `reset` options, but I don't know if those are quite what I'm looking for?

**Comment by altsem** [comment]
It is not implemented yet, but should be possible to implement!
Would probably want to implement a "reverting" state for the status page (as done for rebase/merge status [here](https://github.com/altsem/gitu/blob/f04b4e83ab0eaadf0d328e8089ab0c54c5b00fe8/src/git/mod.rs#L20) :see_no_evil: ).

There's two different keybindings in Magit to revert things. I'm not all too familiar with them, but 'V' seems to revert only commits (with more options?). And 'v' is more flexible, able to _reverse_ single hunks or lines.

relates to #18

**Comment by altsem** [comment]
I've implemented `Revert commit` as seen in Magit under the `V` menu.
As well as some Args for Revert, and continue/abort!

**Comment by TheLostLambda** [comment]
Works wonderfully! Thank you! And the new diff display is fantastic too!
