### ISSUE TITLE
gitu fails to open $EDITOR when $EDITOR contains cli arguments

### ISSUE THREAD

**Issue by fs111** [altsem/gitu#112]
On my work mac I have `$EDITOR` set to `/Applications/MacVim.app/Contents/MacOS/Vim -v` which is [MacVim](https://github.com/macvim-dev/macvim). `gitu` does not understand this correctly because it assumes that the content of `$EDITOR` is a path to an executable and nothing else. It should parse this content properly and invoke the command correctly.

**Comment by altsem** [comment]
Ty for reporting this!
I just released 0.13.1 with a fix (found in efc7e32d9e2e63d1e8b9eeeea39d9ee2e92c3b50). I improved the way line:col args are passed as well, hopefully it'll work :)
