### ISSUE TITLE
Alias the `h` key to `?`

### ISSUE THREAD

**Issue by frank-lenormand** [altsem/gitu#124]
Hi,

I intuitively hit <kbd>?</kbd> whenever I want to check a quick help reference.

Maybe that’s because I use <kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>, <kbd>l</kbd> for actual operations in other terminals tools (like my editor).

Would it be possible to alias the <kbd>h</kbd> key to <kbd>?</kbd>?

**Comment by altsem** [comment]
The default binding is `general.root.help_menu = ["h"]`. You could map it to both by doing:
`general.root.help_menu = ["h", "?"]`.

I would, but considering if `?` should be mapped to reverse search if `/` is mapped to search forward.

**Comment by frank-lenormand** [comment]
I didn’t realise I could set this in the user configuration, thanks!
