### ISSUE TITLE
Improve support for tags

### ISSUE THREAD

**Issue by frank-lenormand** [altsem/gitu#125]
Hi,

The log view shows tags only if they happen to point at a revision in view.

The revision view does not show that it is pointed to by a tag.

I didn’t see any obvious way of displaying all the tags in the repository either, maybe I missed it.

It’d be convenient to put more focus on tags:

- display tags in the reference view (they are stored in `.git/refs/tags` after all)
- have a dedicated tag view that shows all the information related to it (signing, annotation…)
- allow jumping to a tag view from the log/revision view
- showing that the current revision in the revision view is pointed to by a tag

**Comment by golden-expiriensu** [comment]
@altsem I think it's worth adding tags to show_refs right?

Also maybe segregate branches on local and remotes like in magit?:
![image](https://github.com/altsem/gitu/assets/83108115/b5a54454-8e9a-4aed-92b3-9f714aad4138)

The issue for me is that in my company we name branches like "feature/JIRA-XXX-quite-long-description-of-the-feature" and pretty often two branches (local and remote) don't fit onto one line
<img width="1710" alt="Screenshot 2567-04-12 at 13 20 38" src="https://github.com/altsem/gitu/assets/83108115/1e181efc-d645-469d-a287-fa4761cd3939">
So having them in two different sections would make it more neat
