### ISSUE TITLE
Web manual

### ISSUE THREAD

**Issue by crmsnbleyd** [altsem/gitu#13]
Great project!

I believe for the median user a web-based manual would be appreciated, something like <https://magit.vc/manual/magit/>. You could host it on github pages.

I could get started on it (along with CI to build the page based on source files) if you have any preference on which tool to use.

**Comment by altsem** [comment]
I think this could be useful. However, Magit has a lot of features, and documentation.
Whereas this project has just started. Some parts of Gitu are maybe more or less likely to change. And some are not yet implemented.

I feel the README is not yet outgrown, and perhaps in the future it'd make more sense.
There's not even releases of Gitu yet.

Let me think about it. :)

**Comment by crmsnbleyd** [comment]
@altsem , this is beyond the purview of this issue, but perhaps you'd like to commit a roadmap in the form of a markdown file so that items can be picked up from there

**Comment by altsem** [comment]
I think this is a good idea, trying to collect my ideas in the form of issues on here.
