### ISSUE TITLE
Git `prefetch/remotes` should always be ignored (`git maintenance start`)

### ISSUE THREAD

**Issue by TheLostLambda** [altsem/gitu#138]
Hello again!

Just a small one this time! I learned about `git maintenance` recently, and enabled it on my repo using `git maintenance start` (https://git-scm.com/docs/git-maintenance), but now I'm seeing all of the (supposed to be invisible) `prefetch/remotes/...`. These are intentionally ignored by commands like `git log`, and I reckon the same should probably be true for `gitu`!

![Screenshot from 2024-04-17 15-14-42](https://github.com/altsem/gitu/assets/6251883/d7fb6244-4c8c-4cef-ae5c-f6023c82018b)

**Comment by altsem** [comment]
/HEAD is already filtered here: https://github.com/altsem/gitu/blob/master/src/items.rs#L172-L174

Perhaps these are visible on the "show_refs" screen as well? (`Y`)

**Comment by TheLostLambda** [comment]
Hi @altsem !

Interestingly, it actually doesn't show up there! (Which I believe is the correct / intended behavior)!

I'll do a quick poke around to make sure it's not hiding elsewhere, then I'll submit a PR!
