### ISSUE TITLE
Semantic versioning and Changelog

### ISSUE THREAD

**Issue by altsem** [altsem/gitu#14]
We'll want this in order to start doing releases.
Likely we'd need to commit to a _commit_ format.

Investigate and implement tooling around this.

**Comment by alerque** [comment]
I highly recommend [`git-cliff`](https://git-cliff.org/) for this. By default it relies on commits following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec, but it can be customized for other usage as well. Conventional commits has some down sides in my view (e.g. verbosity) as well as any commit scheme introducing some friction. But in my view it is worth it.

Note one common pitfall besides just having to get contributors to do anything regular at all is commiters not understanding that the same changeset might have a different commit message depending on the timeline: a `fix:` commit only applies if the thing being fixed has previously been released and hence the next release notes should have a bug fix entry, but if the bug being fixed up is not yet released it might be just a `chore:` or `refactor:` that (depending on your template) might not even get a mention in release notes. But all caveats aside, I've been using it for a number of projects and having a standard to follow and sticking to it sure makes cutting releases a pleasure.

**Comment by alerque** [comment]
Also I've used [commitlint-github-action](https://github.com/wagoid/commitlint-github-action/) to lint commit messages in CI which is quite helpful for dealing with PRs and tipping people off to needing to fix this without so much maintainer intervention.

**Comment by altsem** [comment]
This is great input. Thank you!

**Comment by altsem** [comment]
Played around with release-plz, but was not happy with the result.
Now there's commit linting and a changelog at least :)
Will probably want to tweak these settings later.
