### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by johnd0e** [altsem/gitu#142]
Please provide windows build in Releases.

P.S.
Versions up to 0.15 I was able to compile myself, but now it depends on unstable feature:
```
   Compiling gitu v0.17.1
error[E0658]: use of unstable library feature 'result_option_inspect'
```

**Comment by altsem** [comment]
Would need some more information.

There are binary releases made on Github, and the CI is running tests on windows successfully (using stable rust 1.77.2).

Perhaps an upgrade in rust compiler would solve it, or running with this flag: `cargo build --locked`?

**Comment by johnd0e** [comment]
`rustup update` helped, thanks.
But why then not provide windows build in Releases?

**Comment by altsem** [comment]
You're right, windows releases are actually not made. Should be easy to add 👍

**Comment by altsem** [comment]
This is now available, haven't tested it out properly. @johnd0e

**Comment by johnd0e** [comment]
It works, but.. it is too big: `45505024 Apr 20 16:59 gitu.exe`
The one compiled with `cargo` is more then 10 times smaller: `3719680 Apr 19 21:13 gitu.exe`

**Comment by altsem** [comment]
How do you mean it is too big?
It is bigger because the new release ships with a few syntax parser to support syntax highlighting. Unrelated to being a windows build.
It'd be neat to make it smaller, but there an issue?

**Comment by johnd0e** [comment]
> It is bigger because the new release ships with a few syntax parser to support syntax highlighting.

Alright then.
I found it suspicious, not because it's just bigger, but because it's 12 times bigger.
However, if this is expected, then there's no issue.

**Comment by altsem** [comment]
I added just a few of these parsers, there must be some way to reduce the binary size :thinking:. Ty for the heads up!
