### ISSUE TITLE
Can't show commit content when press enter (panicked at src/syntax_highlight.rs:185:13:)

### ISSUE THREAD

**Issue by micisse** [altsem/gitu#149]
Hi,

I've been tracking this error since I upgraded to the new version. Unable to display the contents of a commit. The video will tell you more

https://github.com/altsem/gitu/assets/56940294/35c6fc20-a69d-4c1b-bed5-c864fa187da0

version: 0.19.0

**Comment by altsem** [comment]
Hmm interesting. Is the contents in a `.tsx` file by any chance or do you have the file extension?

**Comment by micisse** [comment]
@altsem  It's a rust project, but yeah it does contain `.tsx` files. This commit contains `.tsx` files

**Comment by altsem** [comment]
Cool. I noticed I did an oopsie in the code, fix is on the way! (0.19.1) :+1:

**Comment by micisse** [comment]
**[v0.19.1](https://github.com/altsem/gitu/releases/tag/v0.19.1)** fix the bug 🚀
