### ISSUE TITLE
Unable to Commit

### ISSUE THREAD

**Issue by Joe-Zer0** [altsem/gitu#153]
I just downloaded this tool.  It looks amazing by the way, thank you!  I was testing out committing a file, and it failed with the following error.
```
$ git commit
! exited with code: 1
```
I staged the file with 's', but when I try to commit with 'c' on either the file itself, or the "Staged changes" header, I get the error.

I looked for a log file, but was unable to find one.

gitu version 0.19.2 (170c6ef)
cargo 1.77.2 (e52e36006 2024-03-26)
OsName                : Microsoft Windows 10 Enterprise
OsVersion             : 10.0.19045
Windows Terminal Version: 1.19.10821.0
PowerShell 7.4.1

Let me know what other information you would like me to provide.
Thanks for any help!

**Comment by altsem** [comment]
Were you able to stage changes successfully? And can you run `git commit` outside of Gitu?

It's possible to enable logging by running `gitu --log`, this will write a `gitu.log` file to the current dir.

**Comment by Joe-Zer0** [comment]
I am sorry.  This was entirely my fault.  I forgot the repo I chose to test with had a pre-commit hook that was blocking it.  Thank you for your help, and thank you again for this amazing tool!

**Comment by KaKi87** [comment]
Hi,
I have the exact same issue, but I don't have any hooks.
I installed Gitu using `nix-env -iA nixpkgs.gitu` on Debian arm64.
What to do ?
Thanks
