### ISSUE TITLE
did 0.19.2 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [altsem/gitu#168]
👋 looks like the tarball checksum for 0.19.2 release got changed, raise this issue to confirm if there was re-tagging. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/170891

**Comment by altsem** [comment]
Yes there was! The build broke, so I updated it and moved the tag.

Succesful build:
https://github.com/altsem/gitu/actions/runs/8838447743

Perhaps I should prefer bumping a minor version next time..

I haven't looked into how the brew build determines the checksum / produces binaries. What caused the mismatch?

**Comment by chenrui333** [comment]
> I haven't looked into how the brew build determines the checksum / produces binaries. What caused the mismatch?

mostly the retagging caused the artifact change, thus checksum mismatch.
