### ISSUE TITLE
Leading tabs not displayed in diffs

### ISSUE THREAD

**Issue by matta** [altsem/gitu#201]
Using gitu 0.21.0, the diff display seems to collapse tabs to zero width characters. This makes gitu annoying to use with go code, which uses leading tabs for indentation. The screenshots are taken from Alacritty on Debian stable.

(gitu is awesome by the way! A great alternative to firing up Emacs just to get to magit)

Example:

![image](https://github.com/altsem/gitu/assets/37314/048a66e4-9abc-4e91-936c-35f6b05f63f0)

Same repository state using `git diff` in the terminal:

![image](https://github.com/altsem/gitu/assets/37314/5e19c4a5-ff0c-45dc-84d6-ab7b81b4947c)

**Comment by altsem** [comment]
This seems to be an effect of the TUI lib Ratatui we're using.
The fix is easy I suppose, replace tabs with spaces before rendering.

Question just remains: How many spaces?
Might be good enough to hard-code it to 4 for now. :thinking:

**Comment by matta** [comment]
4 spaces works for me. It is what lazygit does by default, too. Thanks!

As far as feature work, making it configurable might be worth it at some point, maybe even through editorconfig by way of the [ec4s](https://github.com/TheDaemoness/ec4rs) crate. That'd be pretty fancy, though.
