### ISSUE TITLE
option to change bar character for non-nerd fonts

### ISSUE THREAD

**Issue by mattly** [altsem/gitu#207]
The bar character used to highlight the current line does not render in any of the non-nerd fonts I use. I instead get the "missing unicode" character similar to https://github.com/altsem/gitu/issues/80

I, personally, don't like the way nerd fonts render darker than the unpatched variant of the same, and most of time I'm using a commercially-available monospace font which I would have to (and haven't) patched with the nerd icons manually.

I'd rather have an option for gitu to use a different character. I would probably go with ▸ `BLACK RIGHT-POINTING SMALL TRIANGLE` but given that different fonts render these things so differently, it might be nice to leave these up to the individual person.

EDIT: just saw #83 ; this is weird. I'm running gitu from homebrew, version `eed0301-modified`, so I suspect brew hasn't gotten the new version yet.

**Comment by altsem** [comment]
I've been thinking of this :) It's easy to add, so I did it!
Fonts are confusing to me too, it seems some fonts just don't include certain symbols.

The PR I linked makes the symbol configurable:
```toml
cursor = { symbol = "▌", fg = "blue" }
selection_bar = { symbol = "▌", fg = "blue", mods = "DIM" }
```

Could be a start!
