### ISSUE TITLE
[Feature request] Support "renamed" status for a file that have been moved/renamed via "git mv"

### ISSUE THREAD

**Issue by meseck** [altsem/gitu#224]
The current behavior is that the renamed file has both statuses "added" for the new name and "deleted" for the old name.

However, using "git status" will display the file with a "renamed" status, clearly indicating that the file was moved or renamed correctly while preserving its history. 

Thanks for this tool, it's awesome! 🚀

**Comment by meseck** [comment]
Sorry that I accidentally opened multiple duplicates of this issue. I really don't know how it happened. 🤷 😅 
I hope it's easy to remove them.

**Comment by altsem** [comment]
Np! This is something I've been wanting to get right. Think there's some "move detection" you can configure in libgit2 to make it work. Haven't looked into it too deep.

**Comment by z0al** [comment]
Calling `find_similar` in `diff_staged` [here](https://github.com/altsem/gitu/blob/a30c2aea8873d1fbf025e80c7355049b56db0f37/src/git/mod.rs#L128) did the trick:

```rust
diff.find_similar(Some(&mut DiffFindOptions::new().renames(true)))?;
```

**Using `git status`**

<img width="663" alt="image" src="https://github.com/user-attachments/assets/0faf8df4-8249-471c-be55-34c47bde8f9e">

**Using `gitu`**

<img width="668" alt="image" src="https://github.com/user-attachments/assets/3775748d-0c1f-47b7-89c5-2b3bbe335ff2">

I tried to adjust the rendering to match the `git status` output e.g. `renamed old_file -> new_file` but my non-existent Rust experience failed me. Any pointers @altsem 😅?  also, the misalignment of the columns is super annoying.

**Comment by altsem** [comment]
Cool! 🙌
That seems pretty easy to introduce, I should have a double-check and test it. I'm sure aligning the text can be done too.
I'll have a check in the coming days when I get the time :)

**Comment by z0al** [comment]
Thanks @altsem. I will open a PR shortly
<img width="668" alt="image" src="https://github.com/user-attachments/assets/59a3e810-7f36-4645-a02f-1fbdb08345e2">
