### ISSUE TITLE
[FEATURE REQUEST] Splitting/editing a hunk when staging

### ISSUE THREAD

**Issue by ziutech** [altsem/gitu#242]
`git add -p` has an option to edit a hunk before staging to choose which changes to include (and sometimes it can automatically split it). It would be nice if `gitu` had something similar. 
Thanks!

**Comment by altsem** [comment]
Right now it's possible to (un)stage individual lines.
It can be a bit clunky since you can't select multiple and (un)stage all at once.

Is your use-case to just have fine control of splitting hunks?
Or would you edit the content within lines to stage something completely different?

**Comment by ziutech** [comment]
> Right now it's possible to (un)stage individual lines.
Oh, I didn't know that. It seems like that's exactly what I need.
