### ISSUE TITLE
Setting ctrl-g for abort impossible

### ISSUE THREAD

**Issue by TLINDEN** [altsem/gitu#255]
I tried to configure `C-g` as the abort key instead of `q` because I am used to it.

This is the setting:
```toml
[bindings]
root.quit = ["ctrl+g", "<esc>"]
```

However, when I start gitu with this setting, abortion of anything including gitu itself is impossible. It seems to regard the binding as `q` doesn't work anymore, but it doesn't respond to `C-g` either.

Would be really nice if that could work.

While we're at it: maybe you consider adding `C-c` as some kind of fallback binding as well?

**Comment by TLINDEN** [comment]
> * The syntax should be `root.quit = ["<ctrl+c>", "<ctrl+g>", "<esc>"]`

Ah, this works like a charm, very nice :)

**Comment by altsem** [comment]
👍 I'll close this. The other issues will address the usability!
