### ISSUE TITLE
New tag with v0.1337.0

### ISSUE THREAD

**Issue by daeho-ro** [altsem/gitu#281]
Hello, I am trying to upgrade Homebrew formula for gitu, and got error with the error.

- https://github.com/Homebrew/homebrew-core/pull/197471

The tag is suddenly changed to v0.1337.0 and not continuous with the previous version v0.27.0, and that is maybe for some tests I guess. Anyway, should we change the update check for the github releases?

Thanks,

**Comment by altsem** [comment]
Shit, i was trying to fix the release pipe. Didn't realise this would affect the homebrew release.
How does it work? Does it poll?
I've deleted the tag.

Thanks for the heads up! :)

**Comment by daeho-ro** [comment]
Default strategy is just to check the version from tag, but it can be changed to check the release with github latest tag. Is it better to fit your case?

**Comment by altsem** [comment]
I think it is fine as-is. I just needed to be aware of it.
Will you be able to undo this release?

**Comment by daeho-ro** [comment]
OK, then let just close the automatic PR, Thank you for the confirmation!
