### ISSUE TITLE
gitu --help results in stair-stepping

### ISSUE THREAD

**Issue by daveman1010221** [altsem/gitu#34]
![Screenshot from 2024-03-05 13-22-09](https://github.com/altsem/gitu/assets/26435768/8905ef36-4b4a-4073-a64b-97e048edb49c)

**Comment by daveman1010221** [comment]
Installed using 'cargo install gitu --locked'.

**Comment by daveman1010221** [comment]
Once the stair-stepping starts, the shell has to be killed to get rid of it.

**Comment by altsem** [comment]
Hi! I tried reproducing this with the latest 0.2.0 gitu in Alacritty / Gnome terminals on Fedora 39, but to no avail. Curious as to what is causing it.
This info is printed [pretty early](https://github.com/altsem/gitu/blob/acd801d69354dbb684a3e4916c52fb5f9b2deeb7/src/main.rs#L17).

**Comment by daveman1010221** [comment]
This is indeed gone in the version I just sources I just pulled from github and built locally. Seems the crate needs to be updated.

**Comment by altsem** [comment]
I made another release now!
