### ISSUE TITLE
Stash commands and status

### ISSUE THREAD

**Issue by altsem** [altsem/gitu#37]
We're missing the stash list on the status page, as well as stash commands.

Start with save / pop / apply.
Some of these commands open up a prompt, like `zz` prompts you to name the stash.
`zp` will also prompt which stash to pop (default to 0, or the marked one).

![image](https://github.com/altsem/gitu/assets/3618477/2ef5c971-988b-4ef8-bd23-5f9583ce1f79)

**Comment by altsem** [comment]
I think keeping the reference to Repository immutable is not a requirement, but makes the code easier to reason about. If it needs to be a Rc<RefCell<Repository>> (I think?), it's not a huge deal.

Had a peek over at Gitoxide and it seems there's no support for it, else it could have been a good segue into starting to use that.

I found the `git` cli function [here](https://github.com/git/git/blob/945115026aa63df4ab849ab14a04da31623abece/builtin/stash.c#L171).
It seems to be referencing `refs/stash`, perhaps there's a way to list these with more nitty-gritty git2 commands?

**Comment by altsem** [comment]
@golden-expiriensu I played around with it a bit, stole some code from the log fn. It lists a lot more than just what `git stash` would, not sure why. But the stash entries are indeed found in there.

```
#[test]
fn stash_list() {
    let repo = Repository::open(".").unwrap();
    let mut revwalk = repo.revwalk().unwrap();
    revwalk.push_ref("refs/stash").unwrap();
    dbg!(revwalk
        .flat_map(|maybe_oid| maybe_oid.and_then(|oid| repo.find_commit(oid)))
        .map(|commit| commit.summary().unwrap().to_string())
        .collect::<Vec<_>>());

    todo!();
}
```

Again, if `git_stash_foreach` proves to be really simple to use, we could compromise and get rid of the immutable reference to Repository!

**Comment by golden-expiriensu** [comment]
I believe I found another way, under the hood git uses reflog to find changes of ref/stash file, so I think `git reflog stash` is a solution
