### ISSUE TITLE
Doesn't support working in Git submodules

### ISSUE THREAD

**Issue by TheLostLambda** [altsem/gitu#53]
Hiya! Thanks for the super cool looking tool! Unfortunately my main project at the moment is set up as a Git submodule of another repository, but it seems like something about that setup is confusing `gitu` and I'm ending up with the following error!

```
Error: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
```
I was able to reproduce the error by creating an empty git repo (using `git init`) then using `git submodule add ...` and adding any other repository into it. `gitu` works in the parent directory, but cd-ing into the new submodule means that `gitu` returns the error above.

Let me know if you'd like any more information, and I look forward to using `gitu` soon!

**Comment by altsem** [comment]
A fix has been released! :package:

**Comment by TheLostLambda** [comment]
Working wonderfully! Thanks for the super quick turnaround!
