### ISSUE TITLE
The rebase command should not use the selected commit as argument directly

### ISSUE THREAD

**Issue by frank-lenormand** [altsem/gitu#60]
Hi,

When running an interactive rebase from the UI, it appears that Gitu runs `git rebase --interactive <commit>`, with _commit_ being whatever reference was selected.

This results in the selected commit not showing up in the upcoming editor, which is surprising to a user unfamiliar with the underlying Git command.

Could we please make it so Gitu runs something along the lines of `git rebase --interactive '<commit>^'`, instead?

I reckon this would open the door to further issues, for example if the selected commit is a merge commit, but the improvement would be appreciated in other cases.

Thanks!

**Comment by altsem** [comment]
:+1: 

I did some testing in magit and it seems that
- interactive rebase always (afaik) picks the parent
- rebase autosquash does not
- it does warn you whenever you are rebasing over merge commits (I guess as they disappear?)

Makes sense that gitu would behave the same (warning about merge commits can be a future thing)
