### ISSUE TITLE
Allow running a custom Gitu startup command from the CLI

### ISSUE THREAD

**Issue by frank-lenormand** [altsem/gitu#62]
Hi,

I often have to type <kbd>l</kbd>, <kbd>l</kbd> upon starting Gitu.

I’d like to be able to create a Git/shell alias that starts Gitu and makes it jump directly to the log view.

I’m not sure what form this would take, but I can think of a couple options:

1. Have a CLI option that allows Gitu to play arbitrary keys passed as parameter, on startup. Example: `gitu -k ll` would start Gitu, and automatically jump to the log view (by interpreting the two <kbd>l</kbd>).
2. Map out the submenus to a CLI subcommand automatically.
    Example: `gitu cmd log current` would start Gitu, which would know the intent is to enter the `log` submenu, then display the current commits. This would avoid having to rely on whatever keys are bound to which menus/options.

Thanks!

**Comment by altsem** [comment]
No worries, it's good to have some ideas and feedback!

> it’s preferable to create a pass-through Gitu command (cmd example in the first message) that may comply with the Git CLI
This could be a lot of work. Some commands utilize `git` directly, but all that involve reading information use `libgit2` (`log current` does). So someone would need to programmatically map all commands to that library anyway.

From what you suggested previously:
> Map out the submenus to a CLI subcommand automatically.
- sounds a lot easier! And perhaps intuitive.

I haven't thought about ranges vs --from / --to much,
one thing that pops up though is that in magit, you can do `log other` and enter a commit/range in a prompt.
![image](https://github.com/altsem/gitu/assets/3618477/ceeac299-acd6-4f96-9773-a49c650a7a88)

We may want to support that in the future while inside the TUI.

I see what you mean about keeping things under `cmd` to keep things from colliding (especially if we're ever to allow users to define their own submenus etc, although I'm not sure we'll ever get there).

Not sure if there's any benefit of doing either:
`gitu cmd log current`
`gitu --cmd "log current"`

**Comment by altsem** [comment]
@frank-lenormand I started working on a module to parse key input, this'll be needed for supporting configurable keybinds.
When it is done, it'd be really easy to implement your first suggestion (`gitu -k ll`).
It doesn't prevent further additions to the CLI, and gets the job done. :)
