### ISSUE TITLE
An option to ask before quitting Gitu

### ISSUE THREAD

**Issue by frank-lenormand** [altsem/gitu#63]
Hi,

Whenever in a view that’s nested several submenus deep, I tend to hammer down the <kbd>q</kbd> (or  <kbd>esc</kbd>) key.

If I hit the key one too many times, Gitu ends up quitting.

I would like it to (optionally) ask for confirmation before quitting.

Alternatives:

- Only quit if <kbd>q</kbd> is hit, not on <kbd>escape</kbd>.
- Have a separate key/combination that jumps back to the main menu (an unwind command)

Thanks!

**Comment by altsem** [comment]
This could be made configurable, could prompt y/n as well!

**Comment by jondysinger** [comment]
I'd like to volunteer to tackle this feature. I created a pull request ([#89](https://github.com/altsem/gitu/pull/89)) to implement the quit confirmation.

**Comment by altsem** [comment]
Available as of v0.9.0!
