### ISSUE TITLE
Support worktrees

### ISSUE THREAD

**Issue by frank-lenormand** [altsem/gitu#64]
Hi,

It’d be nice if Gitu supported worktrees.

Currently, running it in one yield the following error:

```console
$ gitu    
Error: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
```

In a worktree, `.git` is a _file_ that contains the path to the parent repository.

**Comment by altsem** [comment]
@frank-lenormand Which version are you on? Thought I fixed this crash with 0.5.5.
Ah didn't realize it contains a path, that means rebase/merge status would be broken even after 0.5.5.

**Comment by frank-lenormand** [comment]
I installed the latest at the time, which is `v0.6.3`.

In the worktree directory in which I noticed the issue, the `.git` file contains:

```
gitdir: /the/full/path/to/parent/repository
```

**Comment by golden-expiriensu** [comment]
I actually can't reproduce this with v0.9.0, I wonder what steps did you make to get the error?
I've run the following commands:
1. `git worktree add ../gitu_wt/fix-worktrees`
2. `cd ../gitu_wt/fix-worktree`
3. `gitu`
And no errors after that, I also successfully made a commit to test things out

<img width="794" alt="Screenshot 2567-03-23 at 20 25 13" src="https://github.com/altsem/gitu/assets/83108115/e1282695-cc13-47e1-8b2b-322ad8a9392c">
<img width="804" alt="Screenshot 2567-03-23 at 20 27 00" src="https://github.com/altsem/gitu/assets/83108115/6d04ef0a-1215-4baa-9901-95d3f01f7f4a">

**Comment by frank-lenormand** [comment]
The bug was reported for `v0.6.3`.

It seems to be working as expected, now, with `v0.9.1`.

I couldn’t find which specific commit addressed the issue.
