### ISSUE TITLE
Build/install failing with the latest cargo & git branch

### ISSUE THREAD

**Issue by maxking** [altsem/gitu#68]
I am trying to install gitu from both `cargo install` and from `git` master, but both seems to fail with this error:
```
$ cargo install --git https://github.com/altsem/gitu.git --locked
    Updating git repository `https://github.com/altsem/gitu.git`
  Installing gitu v0.6.3 (https://github.com/altsem/gitu.git#60024baf)
    Updating crates.io index
error: failed to select a version for the requirement `chrono = "^0.4.34"`
candidate versions found which didn't match: 0.4.31, 0.4.30, 0.4.29, ...
location searched: crates.io index
required by package `gitu v0.6.3 (/Users/maxking/.cargo/git/checkouts/gitu-5e9804da17feeb18/60024ba)`
```

I looked up the latest versions of `chrono` on cargo index, which looks like is 0.4.35, but that doesn't seem to work either.

**Comment by altsem** [comment]
Is this on nightly? CI is green and I'm unable to reproduce on stable (1.76). Probably should run CI on nightly as well as stable 🤔

**Comment by maxking** [comment]
After updating my Rust toolchains, I don't seem to have the issue anymore. My bad and thanks for quick response.

Looking forward to trying gitu out as a previous Magit user :-)
