### ISSUE TITLE
Allow staging all files under "unstaged changes" at once

### ISSUE THREAD

**Issue by crmsnbleyd** [altsem/gitu#75]
The magit package allows you to do so by "staging" the heading itself, which stages everything under it. For example if changes are made to flake.nix and cargo.toml, pressing `s` on the heading "unstaged changes" will stage both files. You can also unstage all staged files in a similar fashion.

**Comment by altsem** [comment]
@crmsnbleyd I might've solved this in the linked PR. Saw that there's an extra y/n prompt in magit when doing this. I wonder if we should keep the prompt, or if it's just annoying..

**Comment by altsem** [comment]
Actually, this y/n prompt in magit seems a bit inconsistent.. Could add it in the future.
