### ISSUE TITLE
which font is recommend?

### ISSUE THREAD

**Issue by ErnestDong** [altsem/gitu#80]
Thank you for your awesome work. I tried nerd-font(e.g. Jetbrains-mono-nerd-font) and non-nerd font, but none of them works. see the cursor in the following image.

<img width="1157" alt="image" src="https://github.com/altsem/gitu/assets/45593614/b237f672-a1e2-4f74-8f05-d2397177d0bc">

**Comment by altsem** [comment]
It is trying to render this character: `🢒`
I can't reproduce this, neither on https://www.programmingfonts.org/#jetbrainsmono
or when installing JetBrainsMonoNerdFont and running gitu.

Telling from the letter `3` in your screenshot, it seems to not look like JetBrainsMono.

**Comment by altsem** [comment]
Just for reference, i did experience the same issue when viewing the test snapshots on the github app on my iphone. Not sure which font it's using.

**Comment by haznai** [comment]
I have the same issue with Berkeley Mono (no nerd fonts option)
