### ISSUE TITLE
Feature request: create branch on origin when pushing new branch

### ISSUE THREAD

**Issue by mattgallagher92** [altsem/gitu#90]
Thanks for sharing gitu, I love it so far!

When I'm working on a branch that only exists in my local repo and use Magit to push, Magit handles creating the new branch at the destination and setting that branch as the upstream of my local branch. I'd like gitu to do the same.

**Comment by mattgallagher92** [comment]
Title should probably say "on remote" rather than "on origin"

**Comment by altsem** [comment]
Could be the start of #58

**Comment by rynoV** [comment]
Yeah I think this will be a good starting point, I also find this feature useful

**Comment by golden-expiriensu** [comment]
@mattgallagher92  You probably want to add 
```
[push]
	autoSetupRemote = true
```
to your ~/.gitconfig so git will always create a new branch on remote when pushing

**Comment by mattgallagher92** [comment]
Thanks @golden-expiriensu! That doesn't quite seem to do what I wanted. However, that prompted me to look through the docs more closely, and setting [`push.default`](https://git-scm.com/docs/git-config/#Documentation/git-config.txt-pushdefault) to `current` gives me the behaviour that I want :grin: I can then just run a `git push` (either directly or via gitu) and the branch is created on `origin`.

@altsem given that this seems to be behaviour that's configurable within Git, gitu should probably respect the Git config. Perhaps that means that there's no need for gitu to change its behaviour (up to you).

An easier solution could be to document Git config in a "Migrating from Magit" section somewhere. I'd be happy to contribute a README PR.

What course of action do you think is best?

**Comment by altsem** [comment]
From reading the Magit docs and testing this out myself. I believe Magit does utilize these config variables too. But it would prompt and set them for the current repo and remote if not already set.

I still think there's value in doing that!

**Comment by altsem** [comment]
@mattgallagher92 Im still thinking that Gitu could use a user guide. Haven't decided much on how it should look like. But perhaps it's just a matter of giving the README some structure and adding some tips & tricks (like this one).

Feel free to open a PR if you like. I'm open to ideas! :)

**Comment by mattgallagher92** [comment]
Sorry for the delay! The README is great 🙂 happy for you to close this unless you think that there's anything else of value being tracked here

**Comment by altsem** [comment]
> Magit does give you a prompt I believe instead of just outright failing, I still think there's value in that!
> 
> https://magit.vc/manual/magit/The-Two-Remotes.html

Think this is left just.

**Comment by altsem** [comment]
I believe this is now supported as of version `0.26.0`! :tada:
